language: java
install: true

jdk:
  - openjdk11

script:
  - "./gradlew build --scan -s"
  - "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=bgalek_hackserver -Dsonar.organization=bgalek-github -Dsonar.host.url=https://sonarcloud.io"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
