javers:
  mappingStyle: BEAN
  algorithm: AS_SET

application:
  name: chi-server

discovery:
  enabled: false

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: false

spring:
  resources:
    chain:
      html-application-cache: false

security:
  enabled: true
  rootGroup: "Chibox team"
  oauth2:
    client:
      clientId: client_id
      clientSecret: secret
      accessTokenUri: https://oauth-test.allegrogroup.com/auth/oauth/token
      userAuthorizationUri: https://oauth-test.allegrogroup.com/auth/oauth/authorize
      tokenName: oauth_token
      logoutUri: https://oauth-test.allegrogroup.com/logout
    resource:
      jwt.key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqKzg5f5OW6VK0soaHnKq\n/gflnOLfWXw/UK/9RhsUrp5AgSQtjhjZYUhsRCSuw4QWvBMLJoncukGDCiP78PUH\nTDVFQd284TEgfq2fayduitAnJUJGsqf4mUl29ssGjBVRrRxX4nEnT5iEipkK2rY9\nlxwHw8mV/+/xS4CSSAdy92B/vay6AiB1JxQN3zHnqiGLBNd+UEeqTGr+nmIm+fVC\n5WpxJRwK9rYI3a3pgHamxknN+kL4XSjvTKdOWk0w039U0Nb5gqDTubrqyGswjiNK\nhjXsa/9IdSlp2+wEg/MOFivtID/jnXlEUeRJ3CyXHvR7Za98Krk5g9EU3MqwMsT8\nEwIDAQAB\n-----END PUBLIC KEY-----\n"

chi:
  experiments:
    file: "http://assets-chi.qxlint/chi-server/experiments-test.json"
  crisis-management:
    enabled: false
    whitelist: metrum

interactions:
  repository: kafka
  kafka:
    bootstrap-servers-dc5: kasiatestdc4-cbroker1.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker2.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker3.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker4.kasia-test.pl-kra-3.dc4.local:9092
    bootstrap-servers-dc4: kasiatestdc4-cbroker1.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker2.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker3.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker4.kasia-test.pl-kra-3.dc4.local:9092
    topic: pl.allegro.experiments.chi.interactions.Interaction_avro
    send-timeout: 100
    batch-size: 10000
    linger-ms: 10

avro:
  enabled: true
  serializer: jackson
  schema:
    applicationSchemaProvider: classpath
    registry.location: http://schema-registry-test.allegrogroup.com
    mapping:
      - className: pl.allegro.experiments.chi.chiserver.domain.interactions.Interaction
        schemaVersion: 1
        schemaLocation: /avro/pl.allegro.experiment.chi.chiserver.interactions.Interaction.avsc
        remoteSchemaSubject: pl.allegro.experiments.chi.interactions.Interaction

druid:
  apiHost: druidbroker-nga-test.allegrogroup.com
  experimentsCube: chi_experiments_test
  experimentsStatsCube: chi_experiments_stats_test