application:
  name: chi-server

discovery:
  enabled: false

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: false

chi:
  experiments:
    file: "http://assets-chi.qxlint/chi-server/experiments-test.json"
