discovery:
  enabled: true
  type: consul

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: true
    host: skystats.qxlint

chi:
  experiments:
    file: "http://assets-chi.qxlint/chi-server/experiments-prod.json"