application:
  name: chi-server

discovery:
  enabled: false

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: false

chi:
  experiments:
    file: "http://assets-chi.qxlint/chi-server/experiments-test.json"

interactions:
  repository: local
  buffer-size: 10000
  flush-period: 500

avro:
  enabled: true
  serializer: jackson
  schema:
    applicationSchemaProvider: classpath
    registry.location: http://schema-registry-test.allegrogroup.com
    mapping:
      - className: pl.allegro.experiments.chi.chiserver.interactions.Interaction
        schemaVersion: 1
        schemaLocation: /avro/pl.allegro.experiment.chi.chiserver.interactions.Interaction.avsc
        remoteSchemaSubject: pl.allegro.experiments.chi.interactions.Interaction