application:
  name: chi-server

discovery:
  enabled: false

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: false

chi:
  experiments:
    file: "http://assets-chi.qxlint/chi-server/experiments-test.json"
  client:
    name: assets-chi


assignments.kafka:
  topic: pl.allegro.experiments.chi.assignments_avro

avro:
  enabled: true
  serializer: jackson
  schema:
    applicationSchemaProvider: classpath
    mapping:
      - className: pl.allegro.experiments.chi.chiserver.assignments.ExperimentAssignmentEvent
        schemaVersion: 1
        schemaLocation: /avro/pl.allegro.experiment.chi.chiserver.assignments.ExperimentAssignmentEvent.avsc
#TODO fill that with kafka brokers
spring:
  kafka:
    bootstrap-servers:

hermes:
  url: service://hermes
  client:
    name: hermes

assignments.hermes:
  topic: pl.allegro.experiments.chi.assignments
  schemaVersion: 1
