application:
  name: chi-server

discovery:
  enabled: false

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: false

chi:
  experiments:
    file: "http://assets-chi.qxlint/chi-server/experiments-test.json"

interactions:
  repository: kafka
  kafka:
    bootstrap-servers-dc5: kasiatestdc4-cbroker1.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker2.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker3.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker4.kasia-test.pl-kra-3.dc4.local:9092
    bootstrap-servers-dc4: kasiatestdc4-cbroker1.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker2.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker3.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker4.kasia-test.pl-kra-3.dc4.local:9092
    topic: pl.allegro.experiments.chi.interactions.Interaction_avro
    send-timeout: 100
    batch-size: 10000
    linger-ms: 10

avro:
  enabled: true
  serializer: jackson
  schema:
    applicationSchemaProvider: classpath
    registry.location: http://schema-registry-test.allegrogroup.com
    mapping:
      - className: pl.allegro.experiments.chi.chiserver.interactions.Interaction
        schemaVersion: 1
        schemaLocation: /avro/pl.allegro.experiment.chi.chiserver.interactions.Interaction.avsc
        remoteSchemaSubject: pl.allegro.experiments.chi.interactions.Interaction

druid:
  apiHost: druidbroker-nga-test.allegrogroup.com