discovery:
  enabled: true
  type: consul

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: true
    host: skystats-test.qxlint

druid:
  datasource: chi_experiments_stats_test