interactions:
  repository: local

eventDefinitions:
  repository: local

kafkaCommon:
  kafkaTemplate: off

security:
  enabled: false

spring:
  data:
    mongodb:
        database: chi-server
        host: "localhost"