javers:
  mappingStyle: BEAN
  algorithm: AS_SET

application:
  name: chi-server

discovery:
  enabled: false

metadata:
  cloud:
    skipReading: true

metrics:
  graphite:
    enabled: false

spring:
  resources:
    chain:
      html-application-cache: false

security:
  enabled: true
  rootGroup: "_gr_antifraud_purchase_limits_ru"
  oauth2:
    client:
      clientId: client_id
      clientSecret: secret
      accessTokenUri: https://oauth-dev.allegrogroup.com/auth/oauth/token
      userAuthorizationUri: https://oauth-dev.allegrogroup.com/auth/oauth/authorize
      tokenName: oauth_token
      logoutUri: https://oauth-dev.allegrogroup.com/logout
    resource:
      jwt.key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqKzg5f5OW6VK0soaHnKq\n/gflnOLfWXw/UK/9RhsUrp5AgSQtjhjZYUhsRCSuw4QWvBMLJoncukGDCiP78PUH\nTDVFQd284TEgfq2fayduitAnJUJGsqf4mUl29ssGjBVRrRxX4nEnT5iEipkK2rY9\nlxwHw8mV/+/xS4CSSAdy92B/vay6AiB1JxQN3zHnqiGLBNd+UEeqTGr+nmIm+fVC\n5WpxJRwK9rYI3a3pgHamxknN+kL4XSjvTKdOWk0w039U0Nb5gqDTubrqyGswjiNK\nhjXsa/9IdSlp2+wEg/MOFivtID/jnXlEUeRJ3CyXHvR7Za98Krk5g9EU3MqwMsT8\nEwIDAQAB\n-----END PUBLIC KEY-----\n"

chi:
  experiments:
    file: "http://assets-chi.qxlint/chi-server/experiments-test.json"
  crisis-management:
    enabled: false
    whitelist: metrum

kafka:
  template: "on"
  bootstrap-servers-dc5: kasiatestdc4-cbroker1.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker2.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker3.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker4.kasia-test.pl-kra-3.dc4.local:9092
  bootstrap-servers-dc4: kasiatestdc4-cbroker1.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker2.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker3.kasia-test.pl-kra-3.dc4.local:9092,kasiatestdc4-cbroker4.kasia-test.pl-kra-3.dc4.local:9092
  send-timeout: 100
  batch-size: 10000
  linger-ms: 100

interactions:
  repository: kafka
  kafka:
    topic: pl.allegro.experiments.chi.interactions.Interaction_avro

eventDefinitions:
  repository: kafka
  kafka:
    topic: pl.allegro.experiments.chi.experiments.EventDefinition_avro

avro:
  enabled: true
  serializer: jackson
  schema:
    applicationSchemaProvider: classpath
    registry.location: http://schema-registry-test.allegrogroup.com
    mapping:
      - className: pl.allegro.experiments.chi.chiserver.domain.interactions.Interaction
        schemaVersion: 1
        schemaLocation: /avro/pl.allegro.experiment.chi.chiserver.interactions.Interaction.avsc
        remoteSchemaSubject: pl.allegro.experiments.chi.interactions.Interaction
      - className: pl.allegro.experiments.chi.chiserver.infrastructure.avro.AvroEventDefinition
        schemaVersion: 1
        schemaLocation: /avro/pl.allegro.experiment.chi.chiserver.experiments.EventDefinition.avsc
        remoteSchemaSubject: pl.allegro.experiments.chi.experiments.EventDefinition

status:
  endpoints:
    whitelist:
      resources:
        - GET

notificator:
  enabled: false