interactions:
  repository: local

eventDefinitions:
  repository: local

kafka:
  tempalte: "off"

security:
  enabled: false

spring:
  data:
    mongodb:
        database: chi-server
        host: "localhost"

notificator:
  enabled: true
  hipChatPostUrl: https://allegro.hipchat.com/v2/room/4710838/notification?auth_token=0PO6dZUgmlOfoZ3YWSYPB4bI7XeSLxAXT6UavZdl
