interactions:
  repository: local

security:
  enabled: false

spring:
  data:
    mongodb:
        host: "dev0-mongos1.dc5.alledc.net"
        database: chi_server_d
        username: chi_server_d
        password: uogUo3knLzKV3qL9
