interactions:
  repository: local

eventDefinitions:
  repository: local

kafka:
  tempalte: "off"

security:
  enabled: true

spring:
  data:
    mongodb:
        database: chi-server
        host: "localhost"
