interactions:
  repository: local

eventDefinitions:
  repository: local

kafka:
  tempalte: "off"

security:
  enabled: false

spring:
  data:
    mongodb:
        database: chi-server
        host: "localhost"

email-notifier:
  emailNotificationUrl: service://notificationstwo
  path: /sender/send
  callerId: chi-server
  recipients:
    - aaa@allegro.pl

oauth:
  serviceUrl: service://allegro-auth-service
  path: /auth/oauth/token
  encodedCredentials: Y2hpLXNlcnZlcjpidVZLWlJSbmVwM1NsNkU5QkNaSDBrc2lzV0NYU2RYMlNKV1QzOGtSTmhXRG9CNW1sVXRtZEs4eFg5YWl6UFU5